name: Add Repo to Archives

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'GitHub repo ID (owner/repo) or an owner/org to bulk-add'
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: jbangdev/jbang-action@v0.109.0
        with:
          script: archiver.java
          scriptargs: add -T=${{ secrets.AA_TOKEN }} -W=${{ secrets.AA_DISCORD }} ${{ github.event.inputs.repo }}
        env:
          JBANG_REPO: /root/.jbang/repository

      - uses: stefanzweifel/git-auto-commit-action@v5
        if: always()
        with:
          commit_message: Archived ${{ github.event.inputs.repo }}
          file_pattern: 'data.json'
