name: Sync Archives

on:
  schedule:
    - cron: '48 2,14 * * *'
  workflow_dispatch:


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - uses: jbangdev/jbang-action@v0.109.0
        with:
          script: archiver.java
          scriptargs: sync -T=${{ secrets.AA_TOKEN }} -W=${{ secrets.AA_DISCORD }}
        env:
          JBANG_REPO: /root/.jbang/repository

      - name: Can't bother fixing this issue
        run: rm -f .git/COMMIT_EDITMSG

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Synced archives with upstream.