name: Sync Archives

on:
  schedule:
    - cron: '48 2,14 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: jbangdev/jbang-action@v0.109.0
        with:
          script: archiver.java
          scriptargs: sync -T=${{ secrets.AA_TOKEN }} -W=${{ secrets.AA_DISCORD }}
        env:
          JBANG_REPO: /root/.jbang/repository

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Synced archives with upstream.
          file_pattern: 'state.json data.json'
